{{- if (include "livebook.auth.createSecret" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  livebookPassword: {{ .Values.auth.livebookPassword | required "Either `.Values.auth.livebookPassword` or `.Values.auth.existingSecret` must be provided." }}
{{- end }}
{{- with (include "livebook.clustering.createSecret" . | fromYaml) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-clustering" (include "common.names.fullname" $) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- . | toYaml | nindent 2  }}
{{- end }}
{{- with (include "livebook.networking.createSecret" . | fromYaml) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-networking" (include "common.names.fullname" $) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- . | toYaml | nindent 2  }}
{{- end }}