apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.livebook.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.livebook.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.livebook.service.type }}
  {{- if and (eq .Values.livebook.service.type "ClusterIP") .Values.livebook.service.clusterIP }}
  clusterIP: {{ .Values.livebook.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.livebook.service.type "LoadBalancer") (eq .Values.livebook.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.livebook.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.livebook.service.type "LoadBalancer") .Values.livebook.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.livebook.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if and (eq .Values.livebook.service.type "LoadBalancer") (not (empty .Values.livebook.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.livebook.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: livebook-main
      port: {{ .Values.livebook.service.ports.livebook }}
      targetPort: livebook-main
      {{- if and (or (eq .Values.livebook.service.type "NodePort") (eq .Values.livebook.service.type "LoadBalancer")) (not (empty .Values.livebook.service.nodePorts.api)) }}
      nodePort: {{ .Values.livebook.service.nodePorts.api }}
      {{- else if eq .Values.livebook.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.livebook.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.livebook.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.livebook.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.livebook.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: livebook-main
      port: {{ .Values.livebook.service.ports.livebook }}
      targetPort: livebook-main
      {{- if and (or (eq .Values.livebook.service.type "NodePort") (eq .Values.livebook.service.type "LoadBalancer")) (not (empty .Values.livebook.service.nodePorts.api)) }}
      nodePort: {{ .Values.livebook.service.nodePorts.api }}
      {{- else if eq .Values.livebook.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.livebook.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.livebook.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}